begin;
create extension if not exists pgtap with schema extensions;
set search_path=public,extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at)
select ('51500000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid,'task015b-'||n||'@unc.edu',now() from generate_series(1,4) n;
insert into storage.objects(bucket_id,name,owner_id)
select 'profile-photos',id::text||'/primary.png',id::text from public.accounts where id::text like '51500000-%';
update public.profiles set real_name='Notice fixture',major='Science',graduation_year=2028,
 bio='Local test',primary_photo_path=user_id::text||'/primary.png' where user_id::text like '51500000-%';
update private.hangout_feature_gate set enabled=true;
update private.hangout_chat_feature_gate set enabled=true;
create function pg_temp.hid() returns uuid language sql as $$select current_setting('notice.hangout')::uuid$$;
create function pg_temp.st() returns timestamptz language sql as $$select current_setting('notice.start')::timestamptz$$;
create function pg_temp.key(n integer) returns uuid language sql as $$select ('51500000-0000-4000-8001-'||lpad(n::text,12,'0'))::uuid$$;
create function pg_temp.fail_private() returns trigger language plpgsql as $$begin if new.instructions='FORCE_ROLLBACK' then raise exception 'test private failure'; end if; return new; end;$$;
create trigger notice_private_fail before insert or update on public.hangout_private_locations for each row execute function pg_temp.fail_private();
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"51500000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select set_config('notice.start',(now()+interval '1 hour')::text,true);
select set_config('notice.hangout',public.create_hangout(pg_temp.key(1),'Tacos',pg_temp.st(),'Area',35,-79)::text,true);
select throws_ok($$select private.notification_emit_hangout(gen_random_uuid(),pg_temp.hid(),auth.uid(),'hangout_edited')$$,'42501',null,'client cannot forge event helper');
select throws_ok($$insert into private.notification_items default values$$,'42501',null,'client cannot insert ledger');
select throws_ok($$select * from public.list_notifications()$$,'42501',null,'off notification gate denies inbox');
reset role;
select is((select count(*) from private.notification_items),0::bigint,'create has no notice');
update private.notification_feature_gate set enabled=true;
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"51500000-0000-4000-8000-000000000002","role":"authenticated"}',true);
select public.join_hangout(pg_temp.hid());
select public.join_hangout(pg_temp.hid());
select is((select count(*) from public.list_notifications()),0::bigint,'joiner receives no self notice');
select set_config('request.jwt.claims','{"sub":"51500000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select is((select count(*) from public.list_notifications() where event_code='hangout_joined'),1::bigint,'host gets one actual join');
select is((select actor_id from public.list_notifications() where event_code='hangout_joined'),null::uuid,'host notice hides attendee actor');
select is((select label from public.list_notifications() where event_code='hangout_joined'),'Someone joined your Hangout','host wording generic');
select is(public.edit_hangout(pg_temp.hid(),1,' Tacos ',pg_temp.st(),'Area',35,-79),2::bigint,'normalized no-op revision advances');
select is((select count(*) from public.list_notifications() where event_code='hangout_edited'),0::bigint,'no-op edit emits no item');
select is(public.edit_hangout(pg_temp.hid(),2,'Tacos',pg_temp.st(),'Area',35,-79,p_private_instructions=>'  Secret room  '),3::bigint,'private null to value');
select is(public.edit_hangout(pg_temp.hid(),3,'Tacos',pg_temp.st(),'Area',35,-79,p_private_instructions=>'Secret room'),4::bigint,'private normalized no-op');
select is(public.edit_hangout(pg_temp.hid(),4,'Tacos',pg_temp.st(),'Area',35,-79),5::bigint,'private value to null');
select throws_ok($$select public.edit_hangout(pg_temp.hid(),4,'Wrong',pg_temp.st(),'Area',35,-79)$$,'40001',null,'stale edit denied');
select throws_ok($$select public.edit_hangout(pg_temp.hid(),5,'Failed',pg_temp.st(),'Area',35,-79,p_private_instructions=>'FORCE_ROLLBACK')$$,'P0001',null,'private write failure aborts edit');
select is((select title from public.hangouts where id=pg_temp.hid()),'Tacos','failed edit rolls public row back');
reset role;
select is((select count(*) from private.notification_items where event_code='hangout_edited'),2::bigint,'two material private edits only');
select is((select count(*) from private.notification_items where event_code='hangout_edited' and actor_id='51500000-0000-4000-8000-000000000001'),2::bigint,'server host actor');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"51500000-0000-4000-8000-000000000002","role":"authenticated"}',true);
select is((select count(*) from public.list_notifications() where event_code='hangout_edited'),2::bigint,'joined recipient sees edits');
select ok((select bool_and(actor_id='51500000-0000-4000-8000-000000000001'::uuid) from public.list_notifications() where event_code='hangout_edited'),'edit actor is host');
select ok((select position('Secret' in string_agg(row_to_json(x)::text,' '))=0 from public.list_notifications() x),'inbox copies no private detail');
select public.leave_hangout(pg_temp.hid());
select is((select count(*) from public.list_notifications() where event_code='hangout_edited'),0::bigint,'left recipient edit items neutral');
select is((select count(*) from public.list_notifications() where label='Unavailable'),2::bigint,'old edits unavailable');
select public.join_hangout(pg_temp.hid());
select set_config('request.jwt.claims','{"sub":"51500000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select is((select count(*) from public.list_notifications() where event_code='hangout_joined'),2::bigint,'rejoin gets new identity');
select is((select count(distinct source_id) from public.list_notifications() where event_code='hangout_joined'),2::bigint,'join identities distinct');
select is((select count(*) from public.list_notifications() where event_code='hangout_left'),1::bigint,'actual leave gets host item');
select set_config('request.jwt.claims','{"sub":"51500000-0000-4000-8000-000000000003","role":"authenticated"}',true);
select public.join_hangout(pg_temp.hid());
select set_config('request.jwt.claims','{"sub":"51500000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select is((select count(*) from public.send_hangout_message(pg_temp.hid(),pg_temp.key(2),'Private body')),1::bigint,'message committed');
select is((select count(*) from public.send_hangout_message(pg_temp.hid(),pg_temp.key(2),'Private body')),1::bigint,'message retry returns same');
reset role;
select is((select count(*) from private.notification_items where event_code='hangout_chat_message'),2::bigint,'one chat event to each joined peer');
select is((select count(distinct source_id) from private.notification_items where event_code='hangout_chat_message'),1::bigint,'chat recipients share message ID');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"51500000-0000-4000-8000-000000000004","role":"authenticated"}',true);
select is((select count(*) from public.list_notifications()),0::bigint,'nonparticipant receives nothing');
select set_config('request.jwt.claims','{"sub":"51500000-0000-4000-8000-000000000002","role":"authenticated"}',true);
select is((select event_code from public.list_notifications() limit 1),'hangout_chat_message','joined chat target resolves');
select ok((select position('Private body' in string_agg(row_to_json(x)::text,' '))=0 from public.list_notifications() x),'inbox copies no message body');
select public.set_notification_preference('hangout_updates',false);
select set_config('request.jwt.claims','{"sub":"51500000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select is(public.edit_hangout(pg_temp.hid(),5,'Later',pg_temp.st(),'Area',35,-79),6::bigint,'public detail edit');
reset role;
select is((select count(*) from private.notification_items where event_code='hangout_edited'),3::bigint,'mute suppresses only one of two joined peers');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"51500000-0000-4000-8000-000000000003","role":"authenticated"}',true);
select is((select count(*) from public.list_notifications() where event_code='hangout_edited'),1::bigint,'third joined peer sees new edit');
select set_config('request.jwt.claims','{"sub":"51500000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select public.remove_hangout_participant(pg_temp.hid(),'51500000-0000-4000-8000-000000000003');
select is(public.set_hangout_joining(pg_temp.hid(),6,'closed'),7::bigint,'close joining');
select is(public.set_hangout_joining(pg_temp.hid(),7,'open'),8::bigint,'reopen joining');
reset role;
select is((select count(*) from private.notification_items where event_code='hangout_joined'),3::bigint,'removal and joining state changes emit no host activity');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"51500000-0000-4000-8000-000000000003","role":"authenticated"}',true);
select is((select count(*) from public.list_notifications() where event_code='hangout_edited'),0::bigint,'removed participant edit item neutral');
select throws_ok($$select public.join_hangout(pg_temp.hid())$$,'42501',null,'removed participant cannot rejoin');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"51500000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select public.cancel_hangout(pg_temp.hid(),8);
reset role;
select is((select count(*) from private.notification_items where event_code='hangout_cancelled'),1::bigint,'essential cancellation reaches muted joined peer only');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"51500000-0000-4000-8000-000000000002","role":"authenticated"}',true);
select is((select event_code from public.list_notifications() limit 1),'hangout_cancelled','muted participant sees cancellation');
select is((select count(*) from public.list_notifications() where event_code='hangout_chat_message'),0::bigint,'cancelled chat item unavailable');
select finish();
rollback;
