begin;
create extension if not exists pgtap with schema extensions;
set search_path=public,extensions;
select no_plan();
select is((select count(*) from private.pilot_account_admission),0::bigint,'roster initially empty');
select is((select count(*) from private.pilot_admission_managers),0::bigint,'managers initially empty');
select is((select enabled from private.pilot_availability),false,'availability initially off');
select is((select count(*) from private.pilot_capabilities where not enabled and revision=1),13::bigint,'all fixed capabilities off revision one');
select ok(not private.pilot_is_available(),'private availability helper closed');
select ok(not private.pilot_capability_enabled('unknown'),'unknown capability denied');
select ok(not private.pilot_caller_is_admitted(),'missing caller denied');
select ok(not has_schema_privilege('anon','private','USAGE'),'anon private schema unavailable');
select ok((select bool_and(not has_table_privilege('authenticated','private.'||t,'SELECT,INSERT,UPDATE,DELETE')) from unnest(array['pilot_account_admission','pilot_admission_managers','pilot_availability','pilot_capabilities','pilot_management_audit','pilot_management_requests','pilot_manager_audit']) t),'all private tables lack client grants');
select ok((select bool_and(relrowsecurity) from pg_class where oid in (select ('private.'||t)::regclass from unnest(array['pilot_account_admission','pilot_admission_managers','pilot_availability','pilot_capabilities','pilot_management_audit','pilot_management_requests','pilot_manager_audit']) t)),'all authority tables RLS enabled');
select ok(not has_function_privilege('anon','public.set_pilot_policy(text,boolean,bigint,text,uuid)','EXECUTE'),'anon cannot execute management');
select ok(not has_function_privilege('service_role','private.set_pilot_manager_fixture(uuid,text,bigint,text,uuid)','EXECUTE'),'service role cannot bootstrap manager');
select ok(not has_function_privilege('authenticated','private.pilot_require_manager()','EXECUTE'),'private manager helper not client executable');
select ok(to_regprocedure('public.set_pilot_account_admission(uuid,uuid,text,bigint,text,uuid)') is null,'no fabricated actor signature');
insert into auth.users(id,email,email_confirmed_at)
select ('55000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid,'pilot-sql-'||n||'@unc.edu',now() from generate_series(1,8) n;
update auth.users set email_confirmed_at=null where id='55000000-0000-4000-8000-000000000003';
update auth.users set email='pilot-sql-4@unc.edu.evil.test' where id='55000000-0000-4000-8000-000000000004';
update public.accounts set status='suspended' where id='55000000-0000-4000-8000-000000000005';
insert into public.platform_roles(user_id,role) values('55000000-0000-4000-8000-000000000006','admin');
select is(private.set_pilot_manager_fixture('55000000-0000-4000-8000-000000000001','active',0,'Local test executor',gen_random_uuid()),1::bigint,'trusted manager bootstrap');
select is((select executor_session_user from private.pilot_manager_audit),'postgres','bootstrap records actual executor');
select ok((select executor_original_role in ('none','postgres') and executor_backend_pid=pg_backend_pid() from private.pilot_manager_audit),'original SQL role and backend provenance');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"55000000-0000-4000-8000-000000000002","role":"authenticated"}',true);
select throws_ok($$select * from public.set_pilot_account_admission('55000000-0000-4000-8000-000000000002','active',0,'test',gen_random_uuid())$$,'42501','Pilot management unavailable','ordinary verified user denied');
select throws_ok($$select * from private.pilot_account_admission$$,'42501',null,'direct roster read denied');
select throws_ok($$insert into private.pilot_admission_managers(account_id,state,revision) values(auth.uid(),'active',1)$$,'42501',null,'self manager assignment denied');
select set_config('request.jwt.claims','{"sub":"55000000-0000-4000-8000-000000000006","role":"authenticated"}',true);
select throws_ok($$select * from public.set_pilot_policy('availability',true,1,'test',gen_random_uuid())$$,'42501','Pilot management unavailable','platform admin without manager denied');
reset role;
set local role anon;
select throws_ok($$select private.set_pilot_manager_fixture('55000000-0000-4000-8000-000000000002','active',0,'forge',gen_random_uuid())$$,'42501',null,'actual anon role bootstrap denied');
reset role;
set local role service_role;
select throws_ok($$select private.set_pilot_manager_fixture('55000000-0000-4000-8000-000000000002','active',0,'forge',gen_random_uuid())$$,'42501',null,'actual service_role bootstrap execute denied');
reset role;
grant usage on schema private to service_role;
grant execute on function private.set_pilot_manager_fixture(uuid,text,bigint,text,uuid) to service_role;
set local role service_role;
select throws_ok($$select private.set_pilot_manager_fixture('55000000-0000-4000-8000-000000000002','active',0,'forge',gen_random_uuid())$$,'42501','Pilot management unavailable','original service_role guard independent of execute permission');
reset role;
revoke execute on function private.set_pilot_manager_fixture(uuid,text,bigint,text,uuid) from service_role;
revoke usage on schema private from service_role;
grant usage on schema private to anon;
grant execute on function private.set_pilot_manager_fixture(uuid,text,bigint,text,uuid) to anon;
set local role anon;
select throws_ok($$select private.set_pilot_manager_fixture('55000000-0000-4000-8000-000000000002','active',0,'forge',gen_random_uuid())$$,'42501','Pilot management unavailable','original anon role guard independent of schema and execute permission');
reset role;
revoke execute on function private.set_pilot_manager_fixture(uuid,text,bigint,text,uuid) from anon;
revoke usage on schema private from anon;
-- Grant only inside rolled-back test to prove original-role guard independently
-- of EXECUTE revokes under postgres session SET ROLE authenticated.
grant execute on function private.set_pilot_manager_fixture(uuid,text,bigint,text,uuid) to authenticated;
set local role authenticated;
select throws_ok($$select private.set_pilot_manager_fixture('55000000-0000-4000-8000-000000000002','active',0,'forged',gen_random_uuid())$$,'42501','Pilot management unavailable','SECURITY DEFINER does not erase original-role guard');
reset role;
revoke execute on function private.set_pilot_manager_fixture(uuid,text,bigint,text,uuid) from authenticated;
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"55000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select throws_ok($$select * from public.set_pilot_account_admission('55000000-0000-4000-8000-000000000002','active',0,'AAL1 denied',gen_random_uuid())$$,'42501','Pilot management unavailable','active manager with simulated AAL1 claims denied admission');
select throws_ok($$select * from public.set_pilot_policy('availability',true,1,'AAL1 denied',gen_random_uuid())$$,'42501','Pilot management unavailable','active manager with simulated AAL1 claims denied policy');
select is((select count(*) from storage.objects where owner_id='55000000-0000-4000-8000-000000000002'),0::bigint,'manager authority grants no target storage access');
select is((select count(*) from public.profiles where user_id='55000000-0000-4000-8000-000000000002'),0::bigint,'manager authority grants no target profile access');
select throws_ok($$select * from private.pilot_management_audit$$,'42501',null,'manager cannot directly read private audit');
select throws_ok($$insert into private.pilot_management_audit(actor_id,operation,new_value,previous_revision,new_revision,reason,request_id) values(auth.uid(),'policy','true',0,1,'forge',gen_random_uuid())$$,'42501',null,'manager cannot forge audit');
reset role;
select is((select count(*) from private.pilot_management_requests),0::bigint,'AAL1 denials create no receipts');
select is((select count(*) from private.pilot_management_audit),0::bigint,'AAL1 denials create no management audit');
select is((select enabled from private.pilot_availability),false,'AAL1 denials leave availability closed');
select * from finish();
rollback;
