begin;
create extension if not exists pgtap with schema extensions;
set search_path=public,extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at) values
('60000000-0000-4000-8000-000000000001','owner6@unc.edu',now()),
('60000000-0000-4000-8000-000000000002','peer6@unc.edu',now()),
('60000000-0000-4000-8000-000000000003','unconfirmed6@unc.edu',null);
insert into public.platform_roles values ('60000000-0000-4000-8000-000000000002','admin',now());
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"60000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into storage.objects(bucket_id,name,owner_id) select 'profile-photos',auth.uid()::text||'/'||n||'.png',auth.uid()::text from generate_series(1,6) n;
update public.profiles set real_name='Fixture',major='Biology',bio='Local test',graduation_year=2028,primary_photo_path=auth.uid()::text||'/1.png';
select lives_ok($$update public.profiles set interests=array['Hiking','Music'],down_to_do=array['Tacos'],favorite_music='Jazz',favorite_foods='Noodles',weird_fact='A fact',instagram='test.handle',prompts='[{"question":"Favorite trail?","answer":"Local trail"}]',additional_photo_paths=array[auth.uid()::text||'/2.png',auth.uid()::text||'/3.png',auth.uid()::text||'/4.png',auth.uid()::text||'/5.png']$$,'owner can save full optional profile and four extras');
select is(public.get_access_state(),'ready','optional fields do not alter readiness');
select is((select revision from profiles),2::bigint,'revision advances on every write');
select throws_ok($$update profiles set revision=0$$,'42501',null,'clients cannot overwrite revision');
select throws_ok($$update profiles set interests=array['same','same']$$,'23514',null,'duplicate interests denied');
select throws_ok($$update profiles set interests=array[null]::text[]$$,'23514',null,'null list item denied');
select throws_ok($$update profiles set interests=array[' padded']$$,'23514',null,'untrimmed list item denied');
select throws_ok($$update profiles set interests=array_fill('x'::text,array[11])$$,'23514',null,'eleven items denied');
select throws_ok($$update profiles set down_to_do=array[repeat('x',81)]$$,'23514',null,'long list item denied');
select throws_ok($$update profiles set favorite_foods=''$$,'23514',null,'blank optional text must use null');
select throws_ok($$update profiles set favorite_music=repeat('x',501)$$,'23514',null,'optional text bound');
select throws_ok($$update profiles set weird_fact=' padded '$$,'23514',null,'optional text trimmed');
select throws_ok($$update profiles set instagram='https://instagram.com/a'$$,'23514',null,'Instagram URL denied');
select throws_ok($$update profiles set instagram='@handle'$$,'23514',null,'raw leading at denied');
select throws_ok($$update profiles set prompts='{}'$$,'23514',null,'prompt array required');
select throws_ok($$update profiles set prompts='[null]'$$,'23514',null,'null prompt denied');
select throws_ok($$update profiles set prompts='[{"question":"Q","answer":"A","extra":true}]'$$,'23514',null,'arbitrary prompt keys denied');
select throws_ok($$update profiles set prompts='[{"question":"Q","answer":12}]'$$,'23514',null,'typed prompt strings required');
select throws_ok($$update profiles set prompts='[{"question":"Q","answer":""}]'$$,'23514',null,'empty answer denied');
select throws_ok($$update profiles set additional_photo_paths=array[auth.uid()::text||'/1.png']$$,'23514',null,'primary duplicate denied');
select throws_ok($$update profiles set additional_photo_paths=array[auth.uid()::text||'/2.png',auth.uid()::text||'/2.png']$$,'23514',null,'duplicate extra denied');
select throws_ok($$update profiles set additional_photo_paths=array[auth.uid()::text||'/missing.png']$$,'23514',null,'missing object denied');
select throws_ok($$update profiles set additional_photo_paths=array[auth.uid()::text||'/2.png',auth.uid()::text||'/3.png',auth.uid()::text||'/4.png',auth.uid()::text||'/5.png',auth.uid()::text||'/6.png']$$,'23514',null,'fifth extra denied');
select lives_ok($$update profiles set interests='{}',down_to_do='{}',favorite_music=null,favorite_foods=null,weird_fact=null,prompts='[]',instagram=null,additional_photo_paths='{}'$$,'optional fields clear');
select is(public.get_access_state(),'ready','clearing optional fields keeps readiness');
select set_config('request.jwt.claims','{"sub":"60000000-0000-4000-8000-000000000002","role":"authenticated"}',true);
select is((select count(*) from profiles),1::bigint,'admin sees own draft only');
select throws_ok($$update profiles set additional_photo_paths=array['60000000-0000-4000-8000-000000000001/2.png']$$,'23514',null,'admin cannot reference peer object');
select set_config('request.jwt.claims','{"sub":"60000000-0000-4000-8000-000000000003","role":"authenticated"}',true);
select lives_ok($$update profiles set interests=array['Draft']$$,'unverified active-owner draft semantics preserved');
select is(public.get_access_state(),'unverified','optional data cannot grant verification');
select is((select count(*) from storage.objects where bucket_id='profile-photos'),0::bigint,'unverified has no Storage reads');
reset role;
update accounts set status='banned' where id='60000000-0000-4000-8000-000000000001';
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"60000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select is((select count(*) from profiles),0::bigint,'banned owner no profile reads');
with changed as(update profiles set interests=array['Denied'] returning *) select is(count(*),0::bigint,'banned owner no writes') from changed;
set local role anon;
select throws_ok('select interests from profiles','42501',null,'anonymous profile reads denied');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"60000000-0000-4000-8000-000000000003","role":"authenticated"}',true);
select throws_ok($q$update profiles set interests=array[E'\t']$q$,'23514',null,'tab-only list denied');
select throws_ok($q$update profiles set favorite_foods=E'\n'$q$,'23514',null,'newline-only text denied');
select throws_ok($q$update profiles set prompts=jsonb_build_array(jsonb_build_object('question',E'Q\t','answer','A'))$q$,'23514',null,'tab-padded question denied');
select throws_ok($q$update profiles set weird_fact=U&'\00A0'$q$,'23514',null,'unicode whitespace denied');
select * from finish();
rollback;
